📺say hello to durational stages ⏳
Imbinn/imbinn-engine pull request #1
Opened 2018-11-10 21:35 UTC by bjerkins

I'm segmenting through different stages of rounds based on their duration defined by the data.

2018-11-11 09:51 UTC, bjerkins commented
thanks @codecov !

2018-11-11 14:07 UTC, bjerkins commented
slack is now connected !

2018-11-14 17:43 UTC, AriHrannar commented on src/components/Rounds/Quiz/Text/layout.js
> +                'questioning',
Move to constants and make uppercase

2018-11-14 17:45 UTC, AriHrannar requested changes
Some small thing

2018-11-15 21:54 UTC, merged